### ISSUE TITLE
change working directory, and default user

### ISSUE THREAD

**Issue by jordanst3wart** [blacktop/docker-logstash-alpine#10]
Hi @blacktop 
Would you accept a PR with the default user being non-root, and working directory being changed to `/usr/logstash`?

**Comment by jordanst3wart** [comment]
And maybe changing the jre from 8 to 11?

**Comment by jordanst3wart** [comment]
Just for my personal reference, I think here is the dockerfile for the official logstash image: https://github.com/elastic/logstash/blob/master/docker/templates/Dockerfile.j2

**Comment by blacktop** [comment]
Hi, I'd be down to take a look at a PR.  Sorry for the massive delay in my response.  I prefer staying as close to the official images as possible and just being an alpine drop in if possible.

**Comment by blacktop** [comment]
See if that last commit works for you 😄
