### ISSUE TITLE
Logstash NameError

### ISSUE THREAD

**Issue by daplho** [blacktop/docker-logstash-alpine#3]
Hey @blacktop, I really appreciate your maintaining this repository for logstash alpine images - those have the potential for being the leanest images for logstash. 

Unfortunately, they do present some challenges as well and that's what I'm opening this issue for. I've already written up a detailed account of what's going on on [discuss elastic](https://discuss.elastic.co/t/logstash-could-not-find-any-input-plugin-named-journald-nameerror/97471). Would you mind reviewing that and giving me your opinion on what the issue might be with that particular docker image?

**Comment by blacktop** [comment]
It looks like it works on the official docker image, but not my alpine version?  Is that correct?

**Comment by daplho** [comment]
Yep - that's exactly right. My guess is some library is missing from the alpine produced image.

**Comment by blacktop** [comment]
I have confirmed that alpine does NOT like that plugin 😄  I am not sure why.  I know that alpine does not use `libc` it uses `musl` and that causes a lot of problems.  I will try again this weekend, but using the official docker plugin might be your best bet.

**Comment by daplho** [comment]
Thanks @blacktop, yeah I did some research in the area as well and found several libraries that might be the culprit, `libc` being one of them. Could we replace `musl` in the image?

**Comment by blacktop** [comment]
the entire Alpine OS is based on musl, you can install `libc-compact` but it doesn't seem to help.

I read that journald came out of systemd, and I doubt systemd is installed in alpine as it's init system.

**Comment by daplho** [comment]
@blacktop did you get a chance to do some research here?

**Comment by blacktop** [comment]
> Alpine Linux uses OpenRC for its init system. We have followed suit and added it as the init system in our Alpine Linux base images over systemd. This change allows the containers to seem more like fully fledged Linux environments.

**Comment by blacktop** [comment]
https://j2h2.com/entry/alpine-linux-and-systemd-containers-round-2

**Comment by blacktop** [comment]
https://forum.alpinelinux.org/forum/general-discussion/alpine-plans-systemd

**Comment by blacktop** [comment]
this might work? https://github.com/balabit/syslog-ng/issues/1005

**Comment by blacktop** [comment]
so alpine doesn't like/want to support **systemd** which you need for **journald**, so it might not make sense to have it in alpine.  

Is there a reason for it to be alpine?  I feel like once you add ALL the stuff necessary to get it in alpine the image might have grown to a size comparable to what it would have been on a very slimmed down `ubuntu:xenial` ?

**Comment by daplho** [comment]
Nice research.

No, no specific reason to use alpine. My general effort is to slim down logstash images as much as possible and I'm open to your suggestion of using another pretty slim OS image to accomplish that goal. I will try using `ubuntu:xenial` next and let you know how that goes down.

**Comment by blacktop** [comment]
👍
