### ISSUE TITLE
Logstah confs volume

### ISSUE THREAD

**Issue by uLan08** [blacktop/docker-logstash-alpine#5]
Why did you decided to put volumes for `/etc/logstash/conf.d` ? Having problems with it now. We extended your image and have our own confs, on our Dockerfile we have `COPY ./confs /etc/logstash/conf.d`. Now after rebuilding the image with changes to the logstash conf file, the changes do not take effect because the confs file were mounted and it persisting. Any, workaround for this?

**Comment by blacktop** [comment]
you could also change where logstash will look for logs by uncommenting this line in your image that extends my image:

https://github.com/blacktop/docker-logstash-alpine/blob/master/6.0/config/logstash/logstash.yml#L2

**Comment by uLan08** [comment]
Hmm, but we're not extending the `logstash.yml` file.

**Comment by uLan08** [comment]
Ah, Silly me. Copying the confs file into a different directory and then just pointing `-f /path/to/confs` on run did the trick. Thanks for your time.
