### ISSUE TITLE
what if i get this?

### ISSUE THREAD

**Issue by xulei890817** [blacktop/docker-logstash-alpine#6]
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000002d166, pid=1, tid=0x00007f8065099ae8
#
# JRE version: OpenJDK Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.6.0
# Distribution: Custom build (Tue Nov 21 11:22:36 GMT 2017)
# Problematic frame:
# C  0x000000000002d166
#
# Core dump written. Default location: //core or core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
```

**Comment by blacktop** [comment]
There is not enough detail for me to understand what went wrong.  You might want to ask this in the https://github.com/elastic/logstash repo?

**Comment by xulei890817** [comment]
i try the docker in three diffrent computers both version5.6 and 6.0.
But it comes with the same error.
I hava give it up
I can't find the way to solve it.

**Comment by blacktop** [comment]
What command are you running

**Comment by xulei890817** [comment]
Finally i use the official logstash docker.It works fine.
I don't know why i tried all your versions in three compute both centos and ubuntu,none working for me and  they throw the same error.
Maybe my environment has some unknown force power.
whatever thank you.
